services:
  - type: web
    name: medicinal-plant-identification
    env: python
    buildCommand: |
      # Make the download script executable
      chmod +x download_model.sh
      # Download the model file
      ./download_model.sh
      # Install dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    healthCheckPath: /
    autoDeploy: false
